## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [77]:
import torch
import torch.nn as nn
from collections import OrderedDict

In [78]:
# your code here

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),
    ('output', nn.Linear(2, 2))
]))

model2 = nn.Sequential(OrderedDict([
    ('function1', nn.Linear(2, 4)),
    ('relu1', nn.ReLU()),
    ('function2', nn.Linear(4, 4)),
    ('relu2', nn.ReLU()),
    ('function3', nn.Linear(4, 2)),
    ('sigmoid1', nn.Sigmoid())
]))

model3 = nn.Sequential(OrderedDict([
    ('function1', nn.Linear(2, 3)),
    ('sigmoid1', nn.Sigmoid()),
    ('function2', nn.Linear(3, 2)),
    ('sigmoid2', nn.Sigmoid())
]))

In [79]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (output): Linear(in_features=2, out_features=2, bias=True)
)
Sequential(
  (function1): Linear(in_features=2, out_features=4, bias=True)
  (relu1): ReLU()
  (function2): Linear(in_features=4, out_features=4, bias=True)
  (relu2): ReLU()
  (function3): Linear(in_features=4, out_features=2, bias=True)
  (sigmoid1): Sigmoid()
)
Sequential(
  (function1): Linear(in_features=2, out_features=3, bias=True)
  (sigmoid1): Sigmoid()
  (function2): Linear(in_features=3, out_features=2, bias=True)
  (sigmoid2): Sigmoid()
)


In [80]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)

print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [81]:
# your code here
# data_target = torch.tensor( ...
data_target = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float32)

print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [82]:
# your code here
# criterion = 
# optimizer =

criterion = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

In [83]:
# your code here
# Train the model

num_epochs = 20000
models = {
    1: model1,
    2: model2,
    3: model3,
}
optimizers = {
    1: optimizer1,
    2: optimizer2,
    3: optimizer3,
}
for i in range(1,4):
    print("Model " + str(i))
    for epoch in range(num_epochs):
        output = models[i](data_in)

        loss = criterion(output, data_target)

        optimizers[i].zero_grad()
        loss.backward()
        optimizers[i].step()

        if (epoch + 1) % 100 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Model 1
Epoch [100/20000], Loss: 0.1622
Epoch [200/20000], Loss: 0.1570
Epoch [300/20000], Loss: 0.1564
Epoch [400/20000], Loss: 0.1563
Epoch [500/20000], Loss: 0.1563
Epoch [600/20000], Loss: 0.1563
Epoch [700/20000], Loss: 0.1563
Epoch [800/20000], Loss: 0.1563
Epoch [900/20000], Loss: 0.1563
Epoch [1000/20000], Loss: 0.1563
Epoch [1100/20000], Loss: 0.1563
Epoch [1200/20000], Loss: 0.1563
Epoch [1300/20000], Loss: 0.1562
Epoch [1400/20000], Loss: 0.1562
Epoch [1500/20000], Loss: 0.1562
Epoch [1600/20000], Loss: 0.1562
Epoch [1700/20000], Loss: 0.1562
Epoch [1800/20000], Loss: 0.1562
Epoch [1900/20000], Loss: 0.1562
Epoch [2000/20000], Loss: 0.1563
Epoch [2100/20000], Loss: 0.1562
Epoch [2200/20000], Loss: 0.1562
Epoch [2300/20000], Loss: 0.1562
Epoch [2400/20000], Loss: 0.1562
Epoch [2500/20000], Loss: 0.1562
Epoch [2600/20000], Loss: 0.1562
Epoch [2700/20000], Loss: 0.1562
Epoch [2800/20000], Loss: 0.1562
Epoch [2900/20000], Loss: 0.1562
Epoch [3000/20000], Loss: 0.1562
Epoch [3100

In [84]:
# your code here
# visualize the resuts
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [85]:
# your code here
# print model wights
from datetime import datetime

accuracies = []
models = [model1, model2, model3]
for model in models:
    model.eval()
    start_time = datetime.now()
    with torch.no_grad():
        outputs = model(data_in)
        predicted = (outputs >= 0.5).float()
        print(predicted)
        accuracy = (predicted == data_target).float().mean()
        accuracies.append(accuracy)

    end_time = datetime.now()
    print("Execution time: {}".format(end_time - start_time))
    print("Accuracy: {:.2f}%".format(accuracy.item() * 100))
    print()

# Select the best-performing model
best_model = models[accuracies.index(max(accuracies))]

print('Model ' + str(accuracies.index(max(accuracies)) + 1) + ' is the best!')

tensor([[0., 0.],
        [0., 0.],
        [0., 1.],
        [1., 1.]])
Execution time: 0:00:00.000725
Accuracy: 75.00%

tensor([[0., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])
Execution time: 0:00:00.000336
Accuracy: 75.00%

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Execution time: 0:00:00.000283
Accuracy: 100.00%

Model 3 is the best!
