# Lab 11: Evolutionary computation

### Consider the following example:

Determine the minimum of the function $f(x)= x_1^2+...+x_n^2$ with $x_i \in [-5.12, 5.12]$, $i \in \overline{(1, n)}$

We have an example of steady state genetic algorithm with:  representation an array of real numbers; 100 individuals; crossover $$child = \alpha \cdot (parent1 - parent2) + parent2 ;$$ mutation - reinitialise on a random position the individual's value.

In [103]:


from random import randint, random
from operator import add
from math import cos, pi


def individual(length, vmin, vmax):
    '''
    Create a member of the population - an individual

    length: the number of genes (components)
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    '''
    x = random() * (vmax - vmin) + vmin
    y = random() * (vmax - vmin) + vmin
    return x, y

def population(count, length, vmin, vmax):
    """
    Create a number of individuals (i.e. a population).

    count: the number of individuals in the population
    length: the number of values per individual
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    """
    return [ individual(length, vmin, vmax) for x in range(count) ]

def fitness(individual):
    """
    Determine the fitness of an individual. Lower is better.(min problem)
    For this problem we have the Rastrigin function
    
    individual: the individual to evaluate
    """
    x = individual[0]
    y = individual[1]
    term1 = 100 * np.sqrt(abs(y - 0.01 * x ** 2))
    term2 = 0.01 * abs(x + 10)
    return term1 + term2

def mutate(individual, pM, vmin, vmax):
    '''
    Performs a mutation on an individual with the probability of pM.
    If the event will take place, at a random position a new value will be
    generated in the interval [vmin, vmax]

    individual:the individual to be mutated
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    if pM > random():
            p = randint(0, len(individual)-1)
            individual[p] = random()*(vmax-vmin)+vmin
    return individual

def crossover(parent1, parent2):
    '''
    crossover between 2 parents
    '''
    child=[]
    alpha=random()
    for x in range(len(parent1)):
        child.append(alpha*(parent1[x]-parent2[x])+parent2[x])
    return child

def iteration(pop, pM, vmin, vmax):
    '''
    an iteration

    pop: the current population
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    i1=randint(0,len(pop)-1)
    i2=randint(0,len(pop)-1)
    if (i1!=i2):
        c=crossover(pop[i1],pop[i2])
        c=mutate(c, pM, vmin, vmax)
        f1=fitness(pop[i1])
        f2=fitness(pop[i2])
        '''
        the repeated evaluation of the parents can be avoided
        if  next to the values stored in the individuals we 
        keep also their fitnesses 
        '''
        fc=fitness(c)
        if(f1>f2) and (f1>fc):
            pop[i1]=c
        if(f2>f1) and (f2>fc):
            pop[i2]=c
    return pop

def main(noIteratii=10000):
    #PARAMETERS:

    #population size
    dimPopulation = 100
    #individual size
    dimIndividual = 2
    #the boundries of the search interval
    vmin = -5.12
    vmax = 5.12
    #the mutation probability
    pM=0.01

    P = population(dimPopulation, dimIndividual, vmin, vmax)
    for i in range(noIteratii):
        P = iteration(P, pM, vmin, vmax)

    #print the best individual
    graded = [ (fitness(x), x) for x in P]
    graded =  sorted(graded)
    result=graded[0]
    fitnessOptim=result[0]
    individualOptim=result[1]
    print('Result: The detected minimum point after %d iterations is f(%3.2f %3.2f) = %3.2f'% \
          (noIteratii,individualOptim[0],individualOptim[1], fitnessOptim) )

main()

Result: The detected minimum point after 10000 iterations is f(-1.29 0.02) = 0.09


Exercise 1:  Construct a similar algorithm to the one provided as an example for the Bukin function N.6 (see previous lab for this function).


In [104]:
# your code here
# 100 * np.sqrt(np.abs(y - 0.01*(x * x))) + 0.01 * np.abs(x + 10)

from random import randint, random


def individual(length, vmin, vmax):
    '''
    Create a member of the population - an individual

    length: the number of genes (components)
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    '''
    return [ (random()*(vmax-vmin)+vmin) for x in range(length) ]

def population(count, length, vmin, vmax):
    """
    Create a number of individuals (i.e. a population).

    count: the number of individuals in the population
    length: the number of values per individual
    vmin: the minimum possible value 
    vmax: the maximum possible value 
    """
    return [ individual(length, vmin, vmax) for x in range(count) ]

def fitness(individual):
    """
    Determine the fitness of an individual. Lower is better.(min problem)
    For this problem we have the function f(x,y) = 100 * abs(y - 0.01 * x**2)**0.5 + 0.01 * abs(x + 10)
    
    individual: the individual to evaluate
    """
    x, y = individual[0], individual[1]
    return 100 * abs(y - 0.01 * x**2)**0.5 + 0.01 * abs(x + 10)

def mutate(individual, pM, vmin, vmax):
    '''
    Performs a mutation on an individual with the probability of pM.
    If the event will take place, at a random position a new value will be
    generated in the interval [vmin, vmax]

    individual:the individual to be mutated
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    if pM > random():
            p = randint(0, len(individual)-1)
            individual[p] = random()*(vmax-vmin)+vmin
    return individual

def crossover(parent1, parent2):
    '''
    crossover between 2 parents
    '''
    child=[]
    alpha=random()
    for x in range(len(parent1)):
        child.append(alpha*(parent1[x]-parent2[x])+parent2[x])
    return child

def iteration(pop, pM, vmin, vmax):
    '''
    an iteration

    pop: the current population
    pM: the probability the mutation to occure
    vmin: the minimum possible value 
    vmax: the maximum possible value
    '''
    i1=randint(0,len(pop)-1)
    i2=randint(0,len(pop)-1)
    if (i1!=i2):
        c=crossover(pop[i1],pop[i2])
        c=mutate(c, pM, vmin, vmax)
        f1=fitness(pop[i1])
        f2=fitness(pop[i2])
        '''
        the repeated evaluation of the parents can be avoided
        if  next to the values stored in the individuals we 
        keep also their fitnesses 
        '''
        fc=fitness(c)
        if(f1>f2) and (f1>fc):
            pop[i1]=c
        if(f2>f1) and (f2>fc):
            pop[i2]=c
    return pop

def main(noIteratii=10000):
    #PARAMETERS:

    #population size
    dimPopulation = 100
    #individual size
    dimIndividual = 2
    #the boundries of the search interval
    vmin = -15
    vmax = -5

    #the mutation probability
    pM=0.01

    P = population(dimPopulation, dimIndividual, vmin, vmax)

    for i in range(noIteratii):
        P = iteration(P, pM, vmin, vmax)

    #print the best individual
    graded = [ (fitness(x), x) for x in P]
    graded =  sorted(graded)
    result=graded[0]
    fitnessOptim=result[0]
    individualOptim=result[1]
    print('Result: The detected minimum point after %d iterations is f(%3.2f %3.2f) = %3.2f'% \
          (noIteratii, individualOptim[0], individualOptim[1], fitnessOptim) )

main()

Result: The detected minimum point after 10000 iterations is f(-5.63 -5.15) = 233.91


Consider the knapsack problem:

Consider a Knapsack with a total volum equal with $V_{max}$.

There are $n$ objects, with values $(p_i)_{n}$ and volumes $(v_i)_n$.

Solve this problem using a generationist Genetic Algorithm, with a binary representation.

Exercise 2: Initialization
Objective: Implement the initialization step of a genetic algorithm.

In [105]:
import random

def initialize_population(population_size, chromosome_length):
    # generate random a population with population_size number of individuals
    # each individual with the size chromosome_length
    # IN:  population_size, chromosome_length
    # OUT: population

    # your code here
    population = []
    for i in range(population_size):
        individual = [random.randint(0, 1) for _ in range(chromosome_length)]
        population.append(individual)
    return population

# Test the initialization step
population_size = 10
chromosome_length = 8
population = initialize_population(population_size, chromosome_length)
print(population)


[[0, 1, 1, 0, 0, 0, 0, 1], [0, 1, 0, 1, 1, 1, 0, 0], [1, 1, 0, 0, 0, 0, 1, 1], [1, 1, 0, 1, 0, 0, 0, 1], [1, 1, 0, 0, 1, 1, 0, 0], [0, 0, 1, 0, 1, 1, 1, 1], [1, 0, 1, 1, 1, 0, 0, 0], [1, 0, 0, 1, 1, 0, 0, 0], [1, 1, 0, 1, 1, 0, 1, 0], [0, 1, 0, 0, 1, 1, 0, 0]]


Exercise 3: Fitness Evaluation

Objective: Implement the fitness evaluation step of a genetic algorithm.

In [106]:
values = [15, 23, 8, 10, 12, 7, 20, 11, 18, 14]
weights = [5, 9, 4, 3, 6, 2, 10, 7, 8, 5]
max_weight = 30

def knapsack_fitness(solution):
    total_value = 0
    total_weight = 0

    for i in range(len(solution)):
        if solution[i] == 1:
            total_value += values[i]
            total_weight += weights[i]
    if total_weight > max_weight:
        total_value = 0

    return total_value

def evaluate_fitness(population):
    # evaluate the fitness of each individual in the population
    # IN:  population
    # OUT: fitness_scores

    # your code here
    fitness_scores = []
    for i in range(len(population)):
        fitness_scores.append(knapsack_fitness(population[i]))
    return fitness_scores

# Test the fitness evaluation step
population_size = 10
chromosome_length = 10
population = initialize_population(population_size, chromosome_length)
fitness_scores = evaluate_fitness(population)
print(fitness_scores)


[69, 0, 63, 68, 58, 0, 0, 53, 48, 0]


Exercise 4: Selection

Objective: Implement the selection step of a genetic algorithm.

In [107]:
import numpy as np

def select_parents(population, fitness_scores):
    # select two parents from the population based on the fitness - 
    # the better the fitness, the higher the chance to be selected
    # IN:  population, fitness_scores
    # OUT: selected_parents

    # your code here
    total_fitness = sum(fitness_scores)

    # calculate the probability of each individual to be selected as a parent
    probabilities = [fitness/total_fitness for fitness in fitness_scores]

    # select two parents using Roulette Wheel Selection
    selected_parents = []
    for i in range(2):
        spin = np.random.uniform(0, 1)
        cumulative_probability = 0
        for j in range(len(population)):
            cumulative_probability += probabilities[j]
            if spin <= cumulative_probability:
                selected_parents.append(population[j])
                break

    return selected_parents

# Test the selection step
parents = select_parents(population, fitness_scores)
print(parents)


[[1, 0, 1, 1, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 1, 0, 1, 1, 0, 0]]


Exercise 5: Crossover

Objective: Implement the crossover step of a genetic algorithm.

In [108]:
def crossover(parents):
    # create two new offspring by combining the parents
    # IN:  parents
    # OUT: offspring

    parent1, parent2 = parents
    offspring1 = np.zeros_like(parent1)
    offspring2 = np.zeros_like(parent1)
    point = np.random.randint(1, len(parent1) - 1)
    offspring1[:point] = parent1[:point]
    offspring1[point:] = parent2[point:]
    offspring2[:point] = parent2[:point]
    offspring2[point:] = parent1[point:]

    return offspring1, offspring2

# Test the crossover step
offspring = crossover(parents)
print(offspring)


(array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0]), array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0]))


Exercise 6: Mutation

Objective: Implement the mutation step of a genetic algorithm.

In [109]:
def mutate(chromosome, mutation_rate):
    # mutate the chromosome by randomly flipping bits
    # IN: chromosome, mutation_rate
    # OUT: mutated_chromosome

    mutated_chromosome = chromosome.copy()

    for i in range(len(mutated_chromosome)):
        if random.random() < mutation_rate:
            mutated_chromosome[i] = 1 - mutated_chromosome[i]

    return mutated_chromosome

# Test the mutation step
mutation_rate = 0.1
mutated_offspring = [mutate(child, mutation_rate) for child in offspring]
print(mutated_offspring)


[array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0]), array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])]


Exercise 7: Complete Genetic Algorithm

Objective: Combine all the steps of a genetic algorithm to solve a specific problem.

In [110]:
values = [15, 23, 8, 10, 12, 7, 20, 11, 18, 14]
weights = [5, 9, 4, 3, 6, 2, 10, 7, 8, 5]
max_weight = 30

def initialize_population(population_size, chromosome_length):
    # generate random a population with population_size number of individuals
    # each individual with the size chromosome_length
    # IN:  population_size, chromosome_length
    # OUT: population

    # your code here
    population = []
    for i in range(population_size):
        individual = [random.randint(0, 1) for j in range(chromosome_length)]
        population.append(individual)
    return population

def knapsack_fitness(solution):
    total_value = 0
    total_weight = 0

    for i in range(len(solution)):
        if solution[i] == 1:
            total_value += values[i]
            total_weight += weights[i]
    if total_weight > max_weight:
        total_value = 0

    return total_value

def evaluate_fitness(population):
    # evaluate the fitness of each individual in the population
    # IN:  population
    # OUT: fitness_scores

    # your code here
    fitness_scores = []
    for i in range(len(population)):
        fitness_scores.append(knapsack_fitness(population[i]))
    return fitness_scores

def select_parents(population, fitness_scores):
    # select two parents from the population based on the fitness - 
    # the better the fitness, the higher the chance to be selected
    # IN:  population, fitness_scores
    # OUT: selected_parents

    # your code here
    total_fitness = sum(fitness_scores)

    # calculate the probability of each individual to be selected as a parent
    probabilities = [fitness/total_fitness for fitness in fitness_scores]

    # select two parents using Roulette Wheel Selection
    selected_parents = []
    for i in range(2):
        spin = np.random.uniform(0, 1)
        cumulative_probability = 0
        for j in range(len(population)):
            cumulative_probability += probabilities[j]
            if spin <= cumulative_probability:
                selected_parents.append(population[j])
                break

    return selected_parents

def crossover(parents):
    # create two new offspring by combining the parents
    # IN:  parents
    # OUT: offspring

    parent1, parent2 = parents
    offspring1 = np.zeros_like(parent1)
    offspring2 = np.zeros_like(parent1)
    point = np.random.randint(1, len(parent1) - 1)
    offspring1[:point] = parent1[:point]
    offspring1[point:] = parent2[point:]
    offspring2[:point] = parent2[:point]
    offspring2[point:] = parent1[point:]

    return offspring1, offspring2

def mutate(chromosome, mutation_rate):
    # mutate the chromosome by randomly flipping bits
    # IN:  chromosome, mutation_rate
    # OUT: mutated_chromosome

    # your code here
    for i in range(len(chromosome)):
        if np.random.rand() < mutation_rate:
            chromosome[i] = 1 - chromosome[i]

    return chromosome

def genetic_algorithm(population_size, chromosome_length, generations, mutation_rate):
    # initialize the population
    population = initialize_population(population_size, chromosome_length)

    for _ in range(generations):
        # Fitness evaluation
        fitness_scores = evaluate_fitness(population)

        new_population = []

        # Mutation
        while len(new_population) < len(population):
            # Selection
            parents = select_parents(population, fitness_scores)

            # Crossover
            offspring = crossover(parents)

            offspring_list = [mutate(child, mutation_rate) for child in offspring]

            new_population.append(offspring_list[0])
            new_population.append(offspring_list[1])

        # Replace the population with the new generation
        population = np.array(new_population)

    return population

# Test the complete genetic algorithm
population_size = 10
chromosome_length = 8
generations = 1000
mutation_rate = 0.1

final_population = genetic_algorithm(population_size, chromosome_length, generations, mutation_rate)
print(final_population)


[[1 1 0 0 0 1 0 1]
 [0 0 1 1 0 1 0 1]
 [0 0 1 0 0 1 1 0]
 [0 1 1 0 0 1 0 0]
 [1 0 0 0 0 1 1 0]
 [0 1 1 0 0 1 1 1]
 [0 1 0 0 0 1 1 0]
 [1 1 1 0 0 1 0 0]
 [1 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 1 0]]


Exercise 8: Extract the result from the final population

Objective: Get the best individual from the final population.


In [111]:
# determine the best individual from the final population and print it out

# your code here

population_size = 10
chromosome_length = 8
generations = 100
mutation_rate = 0.1

final_population = genetic_algorithm(population_size, chromosome_length, generations, mutation_rate)

final_fitness = evaluate_fitness(final_population)
individuals = genetic_algorithm(population_size, chromosome_length, generations, mutation_rate)

best_individual = individuals[0]
best_fitness = final_fitness[0]

for i in range(len(final_fitness)):
    if final_fitness[i] > best_fitness:
        best_fitness = final_fitness[i]
        best_individual = individuals[i]

print(best_individual)
print(best_fitness)

[1 1 1 0 0 0 0 1]
74
